name: Lint

on:
    pull_request:
        branches:
            - master

jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Setup node
                uses: actions/setup-node@v3
                with:
                    node-version: 'lts/*'
                    cache: 'yarn'

            -   name: Cache node modules
                uses: actions/cache@v3
                id: cache-modules
                env:
                    cache-name: cache-node-${{ matrix.node }}-modules
                with:
                    path: ./node_modules
                    key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./yarn.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-build-${{ env.cache-name }}-

            -   name: Install dependencies
                if: steps.cache-modules.outputs.cache-hit != 'true'
                run: yarn install --prefer-offline --frozen-lockfile

            -   name: Eslint check and annotate
                uses: sibiraj-s/action-eslint@v2
                with:
                    eslint-args: '--ignore-path .gitignore --quiet'
                    extensions: 'js, jsx, ts, tsx'
                    annotations: true
                    github-token: ${{ secrets.GITHUB_TOKEN }}
